config/routes.rb
Rails.application.routes.draw do
  resources :posts
  root 'home#index'
  #  root 'messages#index'
    resources :messages, only: [:create, :destroy, :index, :new]
  devise_for :users, controllers: {registrations: "registrations"}
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/message.rb
class Message < ApplicationRecord

  belongs_to :sender, class_name: 'User'
  	has_many :recipients
  	has_many :users, :through => :recipients

  	validates :sender_id, presence: true
  
  	validates :body, presence: true

    def user_tokens=(ids)
	    self.user_ids = ids
	end

end

app/models/post.rb
class Post < ApplicationRecord
end

app/models/recipient.rb
class Recipient < ApplicationRecord
  belongs_to :message
	belongs_to :user

	validates :user_id, presence: true
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  has_many :messages, foreign_key: :sender_id



  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable #:confirmable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
    if user_signed_in?
    redirect_to messages_path
  else
    redirect_to new_user_session_path
end
  end
end

app/controllers/messages_controller.rb
class MessagesController < ApplicationController

	def new
		@message = Message.new
		@user = current_user.following
		@users = User.all
	end

	def create
		@message = current_user.messages.build(message_params)

		if @message.save
			flash[:success] = "Message Sent!"
			redirect_to root_path
		else
			flash[:alert] = "Great Scott!"
			render :new
		end
	end

	def index
	@messages = Recipient.where(:user_id => current_user.id).order("created_at DESC")
  #@messages=Message.where(:sender_id =>current_user.id)


	#@rec=Message.where(:sender_id =>current_user.id)
	#	@recipe=Recipient.where(:user_id =>current_user.id)

@s_messages=Message.where(:sender_id =>current_user.id)

	end

	def new
		@message = Message.new
		@recipients = User.all
	end

	private

		def message_params
			params.require(:message).permit(:body, :content, :title, :thumbnail_url, :sender_id, :reciever_id,user_tokens: [])
		end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
    before_action :authenticate_user!
  before_action :set_post, only: [:show, :edit, :update, :destroy]

  # GET /posts
  # GET /posts.json
  def index
    @posts = Post.all
  end

  # GET /posts/1
  # GET /posts/1.json
  def show
  end

  # GET /posts/new
  def new
    @post = Post.new
  end

  # GET /posts/1/edit
  def edit
  end

  # POST /posts
  # POST /posts.json
  def create
    @post = Post.new(post_params)

    respond_to do |format|
      if @post.save
        format.html { redirect_to @post, notice: 'Post was successfully created.' }
        format.json { render :show, status: :created, location: @post }
      else
        format.html { render :new }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /posts/1
  # PATCH/PUT /posts/1.json
  def update
    respond_to do |format|
      if @post.update(post_params)
        format.html { redirect_to @post, notice: 'Post was successfully updated.' }
        format.json { render :show, status: :ok, location: @post }
      else
        format.html { render :edit }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /posts/1
  # DELETE /posts/1.json
  def destroy
    @post.destroy
    respond_to do |format|
      format.html { redirect_to posts_url, notice: 'Post was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_post
      @post = Post.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def post_params
      params.require(:post).permit(:title, :content)
    end
end

app/controllers/registrations_controller.rb
class RegistrationsController < Devise::RegistrationsController
  private
  def sign_up_params
    params.require(:user).permit(:name, :t_user ,:email ,:password , :password_confirmation)
end
def account_update_params
  params.require(:user).permit(:name, :t_user ,:email, :password , :password_confirmation, :current_password)
end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/messages_helper.rb
module MessagesHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/views/home/index.html.erb
<h1>Home#index</h1>
<p>Find me in app/views/home/index.html.erb</p>

app/views/layouts/_header.html.erb
<header>
  <div >
      <%= link_to "Log out", destroy_user_session_path, method: "delete" %>
    <div ><%= link_to 'Chat Ap Assignment', root_path %></div>

    <ul id="js-navigation-menu" class="navigation-menu show">
      <% if user_signed_in? %>

        <div class="btn">


<br/>

          <%= link_to '<button type="button">CHAT</button>'.html_safe, new_message_path%>

          <%= link_to '<button type="button">INBOX</button>'.html_safe, messages_path%>

        <% else %>
          <li class="nav-link"><%= link_to "Sign In", new_user_session_path %></li>
          <li class="nav-link"><%= link_to "Register", new_user_registration_path %></li>
        <% end %>
      </ul>
    </nav>
  </div>
</header>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Login</title>
    <%= csrf_meta_tags %>
  </head>
  <body>
    <%if user_signed_in?%>
      <p>
        Hello,
        <%=current_user.name%>
        This Person is a :
        <%=current_user.t_user%>
        <span></span>

        <%= render 'layouts/header' %>
      </p>
    <%end%>

    <%if !user_signed_in?%>
      <p>
        <%= link_to "Sign IN",new_user_session_path %>
      </p>
    <%end%>

    <%= yield %>
  </body>
</html>

app/views/messages/_message.html.erb
<div >
        <% if message.message.html.present? %>
        <%= message.message.html.html_safe %>
        <% end %>
      </div>
      <div >
        <%= message.message.content %>
      </div>
      <div >
        <div >
          <div >
            <span >

            </span>
            <span >
            <%= link_to message.message.sender.name, message.message.sender %>
            </span>

          </div>
        </div>
      </div>
    </div>


  </div>
<% end %>

app/views/messages/_recipients.html.erb
<div id="stream">
	<%= form_for :message, url: messages_path do |f| %>
		<%= f.text_area :body,  id: "url", placeholder: "Message", class: "message_body" %>

		<div id="stream-list" class="follow-list">
			<ul>
				<% @recipients.each do |user| %>
					<label for="user<%= user.id %>" >
						<li id="stream_item">
							<span><%= user.name %></span>
							<span>  is a  <%= user.t_user %></span>
							<%= check_box_tag "message[user_tokens][]", user.id, @message.users.include?(user), id: "user#{user.id}" %>
						</li>
					</label>
					<br>
				<% end %>
			</ul>
		</div>

		<div id ="stream-footer">
			<%= f.button :submit, class: "btn btn-outline" %>
		</div>

	<% end %>
</div>

app/views/messages/index.html.erb
<div class="bigbox">
	<div class="box">
		<%="THESE are Recieve messages"%>
		<% @messages.each do |message| %>
			<div class="message">
				<div class="top-message">
					<li class="writing"><%= message.message.body %></li>
				</div>

				<div class="bottom-message">
					<span> From      </span><%= message.message.sender.name %>
				</div>
			</div>
		<% end %>

<h4>
<%="THESE are Sent Messages messages"%>
</h4>
<% @s_messages.each do |rec| %>
		<li class="writing"><%= rec.body%></li>


		</li>
<% end %>





	</div>
</div>

app/views/messages/new.html.erb
<div class="form-bigbox">
	<div class="form-box">
		<%= render 'messages/recipients' %>
	</div>
</div>

app/views/posts/_form.html.erb
<%= form_with(model: post, local: true) do |form| %>
  <% if post.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(post.errors.count, "error") %> prohibited this post from being saved:</h2>

      <ul>
      <% post.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :title %>
    <%= form.text_field :title, id: :post_title %>
  </div>

  <div class="field">
    <%= form.label :content %>
    <%= form.text_area :content, id: :post_content %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/posts/edit.html.erb
<h1>Editing Post</h1>

<%= render 'form', post: @post %>

<%= link_to 'Show', @post %> |
<%= link_to 'Back', posts_path %>

app/views/posts/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Posts</h1>

<table>
  <thead>
    <tr>
      <th>Title</th>
      <th>Content</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @posts.each do |post| %>
      <tr>
        <td><%= post.title %></td>
        <td><%= post.content %></td>
        <td><%= link_to 'Show', post %></td>
        <td><%= link_to 'Edit', edit_post_path(post) %></td>
        <td><%= link_to 'Destroy', post, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Post', new_post_path %>

app/views/posts/new.html.erb
<h1>New Post</h1>

<%= render 'form', post: @post %>

<%= link_to 'Back', posts_path %>

app/views/posts/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Title:</strong>
  <%= @post.title %>
</p>

<p>
  <strong>Content:</strong>
  <%= @post.content %>
</p>

<%= link_to 'Edit', edit_post_path(@post) %> |
<%= link_to 'Back', posts_path %>